// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace guveporrtapi.Models;

public partial class AccidentReportStaff
{
    public int IdAccident { get; set; }

    public int IdStaff { get; set; }

    public virtual Accident IdAccidentNavigation { get; set; }

    public virtual Staff IdStaffNavigation { get; set; }
}