// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace guveporrtapi.Models;

public partial class ContractAccident
{
    public int IdContract { get; set; }

    public int IdAccident { get; set; }

    public virtual Accident IdAccidentNavigation { get; set; }

    public virtual Contract IdContractNavigation { get; set; }
}