// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GuvenPortAPI.Models;

public partial class ContractAccident
{
    public int IdContract { get; set; }

    public int IdAccident { get; set; }

    public virtual Accident IdAccidentNavigation { get; set; } = null!;

    public virtual Contract IdContractNavigation { get; set; } = null!;
}