// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace GuvenPortAPI.Models;

public partial class Contract
{
    public int Id { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int? IdWorkplace { get; set; }

    public int? IdEmployee { get; set; }
    [JsonIgnore]
    public virtual ICollection<ContractAccident> ContractAccidents { get; set; } = new List<ContractAccident>();
    [JsonIgnore]
    public virtual Employee? IdEmployeeNavigation { get; set; }
    [JsonIgnore]
    public virtual Workplace? IdWorkplaceNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<MedicalExamination> MedicalExaminations { get; set; } = new List<MedicalExamination>();
}