// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace GuvenPortAPI.Models;

public partial class ContractAccident
{
    public int IdContract { get; set; }

    public int IdAccident { get; set; }
    [JsonIgnore]
    public virtual Accident IdAccidentNavigation { get; set; } = null!;
    [JsonIgnore]
    public virtual Contract IdContractNavigation { get; set; } = null!;
}