// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace GuvenPortAPI.Models;

public partial class ContractAndJob
{
    public int? IdContract { get; set; }

    public string? JobType { get; set; }
    [JsonIgnore]
    public virtual Contract? IdContractNavigation { get; set; }
}