// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace guveporrtapi.Models;

public partial class Contract
{
    public int Id { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int? IdWorkplace { get; set; }

    public int? IdEmployee { get; set; }

    public virtual ICollection<ContractAccident> ContractAccidents { get; set; } = new List<ContractAccident>();

    public virtual Employee IdEmployeeNavigation { get; set; }

    public virtual Workplace IdWorkplaceNavigation { get; set; }

    public virtual ICollection<MedicalExamination> MedicalExaminations { get; set; } = new List<MedicalExamination>();
}