// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GuvenPortAPI.Models;

public partial class Doctor
{
    public int IdStaff { get; set; }

    public virtual Staff IdStaffNavigation { get; set; } = null!;

    public virtual ICollection<MedicalExamination> MedicalExaminations { get; set; } = new List<MedicalExamination>();
}