// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
namespace GuvenPortAPI.Models;

public partial class Doctor
{
    public int IdStaff { get; set; }
    [JsonIgnore]
    public virtual Staff IdStaffNavigation { get; set; } = null!;
    [JsonIgnore]
    public virtual ICollection<MedicalExamination> MedicalExamination { get; set; } = new List<MedicalExamination>();
}