// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using guveporrtapi.Models;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace guveporrtapi.Models
{
    public partial interface IisgportalContextFunctions
    {
    }
}
