// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using GuvenPortAPI.Models;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace GuvenPortAPI.Models
{
    public partial class isgportalContext
    {
        private IisgportalContextFunctions _procedures;

        public virtual IisgportalContextFunctions Functions
        {
            get
            {
                if (_procedures is null) _procedures = new isgportalContextFunctions(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IisgportalContextFunctions GetFunctions()
        {
            return Functions;
        }
    }

    public partial class isgportalContextFunctions : IisgportalContextFunctions
    {
        private readonly isgportalContext _context;

        public isgportalContextFunctions(isgportalContext context)
        {
            _context = context;
        }
    }
}
