// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GuvenPortAPI.Models;

public partial class MedicalExamination
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public bool? IsDisabled { get; set; }

    public DateOnly? ValidityDate { get; set; }

    public int? IdContract { get; set; }

    public int? IdDoctor { get; set; }

    public bool? ExFilePrinted { get; set; }

    public bool? ExIbys { get; set; }

    public string? ExFileLocation { get; set; }

    public bool? ExFilePrintedUploaded { get; set; }

    public virtual Contract? IdContractNavigation { get; set; }

    public virtual Doctor? IdDoctorNavigation { get; set; }
}