// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace guveporrtapi.Models;

public partial class Office
{
    public int Id { get; set; }

    public string Address { get; set; }

    public string OName { get; set; }

    public string Crm { get; set; }

    public bool? Active { get; set; }

    public int? IdManagerstaff { get; set; }

    public virtual Staff IdManagerstaffNavigation { get; set; }

    public virtual ICollection<StaffOffice> StaffOffices { get; set; } = new List<StaffOffice>();

    public virtual ICollection<Workplace> Workplaces { get; set; } = new List<Workplace>();
}