// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GuvenPortAPI.Models;

public partial class StaffExaminationSummary
{
    public int? ExaminationId { get; set; }

    public DateOnly? ExaminationDate { get; set; }

    public string? DoctorName { get; set; }

    public string? EmployeeName { get; set; }

    public int? ExaminationType { get; set; }
}