// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace guveporrtapi.Models;

public partial class StaffWorkplace
{
    public int IdStaff { get; set; }

    public int IdWorkplace { get; set; }

    public virtual Staff IdStaffNavigation { get; set; }

    public virtual Workplace IdWorkplaceNavigation { get; set; }
}