// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GuvenPortAPI.Models;

public partial class Staff
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Ssn { get; set; }

    public string? Password { get; set; }

    public string? Mail { get; set; }

    public DateOnly? Dob { get; set; }

    public bool? Active { get; set; }

    public virtual ICollection<AccidentReportStaff> AccidentReportStaffs { get; set; } = new List<AccidentReportStaff>();

    public virtual Doctor? Doctor { get; set; }

    public virtual ICollection<Office> Offices { get; set; } = new List<Office>();

    public virtual ICollection<StaffOffice> StaffOffices { get; set; } = new List<StaffOffice>();

    public virtual ICollection<StaffWorkplace> StaffWorkplaces { get; set; } = new List<StaffWorkplace>();
}