// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace guveporrtapi.Models;

public partial class StaffOffice
{
    public int IdStaff { get; set; }

    public int IdOffice { get; set; }

    public virtual Office IdOfficeNavigation { get; set; }

    public virtual Staff IdStaffNavigation { get; set; }
}