// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GuvenPortAPI.Models;

public partial class StaffWorkplace
{
    public int IdStaff { get; set; }

    public int IdWorkplace { get; set; }

    public virtual Staff IdStaffNavigation { get; set; } = null!;

    public virtual Workplace IdWorkplaceNavigation { get; set; } = null!;
}