// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
namespace GuvenPortAPI.Models;

public partial class StaffOffice
{
    public int IdStaff { get; set; }

    public int IdOffice { get; set; }
    [JsonIgnore]
    public virtual Office IdOfficeNavigation { get; set; } = null!;
    [JsonIgnore]
    public virtual Staff IdStaffNavigation { get; set; } = null!;
}