// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace GuvenPortAPI.Models;

public partial class StaffWorkplace
{
    public int IdStaff { get; set; }

    public int IdWorkplace { get; set; }
    [JsonIgnore]
    public virtual Staff IdStaffNavigation { get; set; } = null!;
    [JsonIgnore]
    public virtual Workplace IdWorkplaceNavigation { get; set; } = null!;
}