// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace guveporrtapi.Models;

public partial class Workplace
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string SocialSecurityNumber { get; set; }

    public bool? Active { get; set; }

    public string Adress { get; set; }

    public int? IdOffice { get; set; }

    public int? HazardLevel { get; set; }

    public virtual ICollection<Accident> Accidents { get; set; } = new List<Accident>();

    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    public virtual Office IdOfficeNavigation { get; set; }

    public virtual ICollection<StaffWorkplace> StaffWorkplaces { get; set; } = new List<StaffWorkplace>();
}