// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace GuvenPortAPI.Models;

public partial class Workplace
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? SocialSecurityNumber { get; set; }

    public bool? Active { get; set; }

    public string? Adress { get; set; }

    public int? IdOffice { get; set; }

    public int? HazardLevel { get; set; }
    [JsonIgnore]
    public virtual ICollection<Accident> Accidents { get; set; } = new List<Accident>();
    [JsonIgnore]
    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();
    [JsonIgnore]
    public virtual Office? IdOfficeNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<StaffWorkplace> StaffWorkplaces { get; set; } = new List<StaffWorkplace>();
}